name = "Golem"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfaabb78ebfb9c92b711674dbac080db8129d6bd610f4f27b5501c25960c3cf1"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
