name = "Golem"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "996ff62cca2273ba548c1c13e44520863d9f80b2f74bed43ac5234af165bf3e8"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
