name = "Golem"
version = "1.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0756f1c89eeb029333d9dd2214d1d4e5b280ab5f041972c3726a9beae4b7f035"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
